### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by Alwaysuuu** [cong/ros_tensorflow#1]
Traceback (most recent call last):
  File "/home/smile/catkin_ws/src/ros_tensorflow/scripts/ros_tensorflow_detect.py", line 122, in <module>
    tf.import_graph_def(od_graph_def, name='')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 258, in import_graph_def
    op_def = op_dict[node.op]
KeyError: u'TensorArrayV3'

怎么破解啊？

**Comment by cong** [comment]
Sorry, there really doesn't appear this "/usr/local/lib/python2.7/dist-packages/tensorflow/" folder in my system.
Did you compile "Cython" according to the official tutorial?
And you can refer to this issue (https://github.com/tensorflow/models/issues/1603).

**Comment by gw00207** [comment]
I also get this error, with tensorflow 1.7:

  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 227, in _RemoveDefaultAttrs
    op_def = op_dict[node.op]

KeyError: 'GRUBlockCell'

**Comment by cdlwhm1217096231** [comment]
求助，我的也是这个bug@cong

**Comment by cdlwhm1217096231** [comment]
File "/home/pibot/pibot_ros/ros_ws/src/ros_tensorflow/scripts/ros_tensorflow_detect.py", line 116, in <module>
    tf.import_graph_def(od_graph_def, name='')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 280, in import_graph_def
    raise ValueError('No op named %s in defined operations.' % node.op)
ValueError: No op named NonMaxSuppressionV2 in defined operations.

**Comment by cong** [comment]
@cdlwhm1217096231 
I‘m running this code today, and there is no error. How do you build the environment?
今天我在云服务器上运行了这个repo，没有报错，私以为和你配的环境有关...

**Comment by cdlwhm1217096231** [comment]
tensorflow-cpu version1.10

**Comment by cong** [comment]
@cdlwhm1217096231 
```sh
# 安装依赖项
# Dependencies
sudo apt-get install protobuf-compiler python-pil python-lxml
sudo pip install jupyter
sudo pip install matplotlib
```
不知道你这些依赖项安装了没有，若果还是报错的话，建议重新开一个新环境部署测试.
Have you installed those tools and dependencies? And if there is any error with this repo please deploy in a clean environment.

**Comment by cdlwhm1217096231** [comment]
我是在树莓派3上使用的，树莓派3上安装的ubuntu16.04，matplotlib库已经安装了，Python是2.7.12版本的
